site_name: KeepUp Smart - Manuale Ristorante
site_url: https://ivanrobuschi-custom.github.io/keepup-smart/
site_author: Ivan Robuschi

theme:
  name: material
  logo: assets/icons/logo.png
  favicon: assets/icons/favicon.png
  language: it
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
  palette:
    primary: blue grey

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - tags

copyright: Copyright Custom S.p.A 2026

nav:
  - Home: index.md
  - KeepUp Smart (Cassa):
      - Interfaccia principale: pos-interfaccia.md
      - Programmazione articoli: pos-articoli.md
      - Programmazione sale: pos-sale.md
      - Gestione operatori: pos-operatori.md
      - Stampanti fiscali: pos-stampanti.md
      - Statistiche e report: pos-statistiche.md
      - Impostazioni avanzate: pos-impostazioni.md
      - Archivi: pos-archivi.md
  - KeepUp Order (Palmare):
      - Schermata principale: order-home.md
      - Gestione tavoli: order-tavoli.md
      - Inserimento ordini: order-inserimento.md
      - Sincronizzazione: order-sync.md
      - Configurazione palmari: order-configurazione.md
  - Gestione licenze: licenze.md
  - Gestione Monopoli: monopoli.md
